// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToHost(arg1) {
  return window['go']['main']['App']['ConnectToHost'](arg1);
}

export function GetSSHHosts() {
  return window['go']['main']['App']['GetSSHHosts']();
}
